security:
    password_hashers:
        App\Entity\User:
            algorithm: auto
            cost: 4

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Routes d'authentification (pas de JWT)
        api_auth:
            pattern: ^/api/auth/(login|register|forgot-password|reset-password|verify-reset-token)
            stateless: true
            security: false

        # Routes API protégées
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        # Routes publiques
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/verify-reset-token, roles: PUBLIC_ACCESS }
        - { path: ^/api/products, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/categories, roles: PUBLIC_ACCESS, methods: [GET] }

        # Routes authentifiées
        - { path: ^/api/auth/check, roles: ROLE_USER }
        - { path: ^/api/auth/me, roles: ROLE_USER }
        - { path: ^/api/auth/logout, roles: ROLE_USER }
        - { path: ^/api/auth/refresh, roles: ROLE_USER }
        - { path: ^/api/auth/change-password, roles: ROLE_USER }
        - { path: ^/api/cart, roles: ROLE_USER }
        - { path: ^/api/orders, roles: ROLE_USER }
        - { path: ^/api/users, roles: ROLE_USER }

        # Toutes les autres routes API
        - { path: ^/api, roles: ROLE_USER }

# Configuration spécifique pour l'environnement de test
when@test:
    security:
        password_hashers:
            # Hashage simplifié pour les tests (plus rapide)
            App\Entity\User:
                algorithm: auto
                cost: 4 # Valeur la plus basse pour bcrypt
                time_cost: 3 # Valeur la plus basse pour argon
                memory_cost: 10 # Valeur la plus basse pour argon

# Configuration pour la production
when@prod:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: auto
                cost: 15 # Sécurité renforcée en production
                time_cost: 4
                memory_cost: 1024
